spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rokidev.com:5432/postgres
    username: postgres
    password: test1234
  jpa:
    hibernate:
      ddl-auto: create
      jdbc:
        time_zone: Asia/Seoul
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        physical_naming_strategy: com.yrkim.springwithaws.common.tools.hibernate.HibernatePhysicalNamingStrategy
    generate-ddl: true
  messages:
    basename: message
    encoding: UTF-8


logging:
  level:
    org.hibernate.SQL: info
    org.hibernate.type: trace  # 변수값 출력
    org.hibernate.type:descriptor.sql.BasicBinder: TRACE
    org.apache.tomcat: info
    com.yrkim.springsecurity: debug
    org.springframework.transaction: trace  # 트랜젝션 로그 활성화

config:
  downloadImage: http://rokidev.com:10082
  uploadImage: http://rokidev.com:10082

server:
  compression:
    enabled: true
  error:
    include-exception: true
    include-stacktrace: always
    whitelabel:
      enabled: true
  tomcat:
    accesslog:
      enabled: true
      directory: logs/
    basedir: /yrkim_server/logs/tomcat
    max-http-form-post-size: 50MB
  servlet:
    context-path: /
  port: 9000

jwt:
  header: Authorization
  #hello-backend-developer-i-am-yeongroke-jobis-spring-boot-web-project-security-jwt-secret
  secret: aGVsbG8tYmFja2VuZC1kZXZlbG9wZXItaS1hbS15ZW9uZ3Jva2Utam9iaXMtc3ByaW5nLWJvb3Qtd2ViLXByb2plY3Qtc2VjdXJpdHktand0LXNlY3JldA==
